name: CI

on:
  push:
  pull_request:

jobs:
  build_linux:
    runs-on: ubuntu-latest
    steps:
      - name: clone
        run: git clone --recurse-submodules https://git.ardour.org/ardour/ardour.git -b 7.3
      - name: deps
        run: |
          sudo apt install -y \
          liblrdf-dev \
          git \
          autoconf \
          automake \
          libtool \
          pkg-config \
          yasm \
          python \
          gettext \
          libboost-all-dev \
          alsa-base \
          libasound2 \
          libasound2-dev \
          libpulse-dev \
          libsndfile1-dev \
          libglibmm-2.4-dev \
          libcurl4-openssl-dev \
          libarchive-dev \
          liblo-dev \
          libtag1-dev \
          vamp-plugin-sdk \
          librubberband-dev \
          libudev-dev \
          libfftw3-dev \
          libjack-dev \
          libaubio-dev \
          libserd-dev \
          libsord-dev \
          libsratom-dev \
          liblilv-dev
      - name: configure
        working-directory: ardour
        run: ./waf configure
  build_windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: msys2/setup-msys2@v2
        with:
          msystem: mingw64
          update: true
          install: >-
            base-devel
            mingw-w64-x86_64-openssl
            mingw-w64-x86_64-toolchain
            python3
            python3-setuptools
            mingw-w64-x86_64-python3
            mingw-w64-x86_64-python3-setuptools
            pkg-config
            mingw-w64-x86_64-pkg-config
            autoconf
            automake
            perl
            gtk-doc
            flex
            bison
            patch
            libtool
            mingw-w64-x86_64-libtool
            wget
            git
            nasm
            mingw-w64-x86_64-nasm
            dos2unix
            mingw-w64-x86_64-cmake
            mingw-w64-x86_64-glib2
            mingw-w64-x86_64-gobject-introspection
            mingw-w64-x86_64-pkg-config
            mingw-w64-x86_64-c-ares
            mingw-w64-x86_64-ca-certificates
            mingw-w64-x86_64-gnutls
            mingw-w64-x86_64-libidn
            mingw-w64-x86_64-libssh2
            mingw-w64-x86_64-rtmpdump
            mingw-w64-x86_64-gnutls
            libgnutls-devel
            libutil-linux-devel
            gtk-doc
            mingw-w64-x86_64-docbook-xsl
            intltool
            mingw-w64-x86_64-libjpeg-turbo
            mingw-w64-x86_64-jbigkit
            mingw-w64-x86_64-ladspa-sdk
            mingw-w64-x86_64-icu
            mingw-w64-x86_64-boost
            mingw-w64-x86_64-curl
            mingw-w64-x86_64-fftw
            mingw-w64-x86_64-libusb
            mingw-w64-x86_64-libxml2
            mingw-w64-x86_64-libogg
            mingw-w64-x86_64-flac
            mingw-w64-x86_64-libvorbis
            mingw-w64-x86_64-libsndfile
            mingw-w64-x86_64-libsamplerate
            mingw-w64-x86_64-soundtouch
            mingw-w64-x86_64-wineditline
            mingw-w64-x86_64-pcre
            mingw-w64-x86_64-cppunit
            mingw-w64-x86_64-taglib
            mingw-w64-x86_64-dlfcn
            mingw-w64-x86_64-gobject-introspection
            mingw-w64-x86_64-gtk-doc
            mingw-w64-x86_64-gnome-common
            mingw-w64-x86_64-atk
            mingw-w64-x86_64-libpng
            mingw-w64-x86_64-harfbuzz
            mingw-w64-x86_64-cairo
            mingw-w64-x86_64-fontconfig
            mingw-w64-x86_64-freetype
            mingw-w64-x86_64-pixman
            mingw-w64-x86_64-pango
            mingw-w64-x86_64-libjpeg-turbo
            mingw-w64-x86_64-jasper
            mingw-w64-x86_64-libtiff
            mingw-w64-x86_64-shared-mime-info
            mingw-w64-x86_64-gtk2
            mingw-w64-x86_64-libsigc++
            mingw-w64-x86_64-cairomm
            mingw-w64-x86_64-glibmm
            mingw-w64-x86_64-atkmm
            mingw-w64-x86_64-pangomm
            mingw-w64-x86_64-gtkmm
            mingw-w64-x86_64-rubberband
            mingw-w64-x86_64-vamp-plugin-sdk
            mingw-w64-x86_64-meson
            mingw-w64-x86_64-giflib
            mingw-w64-x86_64-libexif
            mingw-w64-x86_64-expat
            mingw-w64-x86_64-libffi
            mingw-w64-x86_64-gettext
            mingw-w64-x86_64-fribidi
            mingw-w64-x86_64-libepoxy
            mingw-w64-x86_64-libgnurx
            mingw-w64-x86_64-ncurses
            mingw-w64-x86_64-gdk-pixbuf2
            mingw-w64-x86_64-libgdiplus
            mingw-w64-x86_64-libarchive
      - name: clone
        run: git clone --recurse-submodules https://git.ardour.org/ardour/ardour.git -b 7.3
      - name: compile
        working-directory: ardour
        env:
          CC: x86_64-w64-mingw32-gcc
          CXX: x86_64-w64-mingw32-g++
          CPP: x86_64-w64-mingw32-cpp
          AR: x86_64-w64-mingw32-ar
          LD: x86_64-w64-mingw32-ld
          NM: x86_64-w64-mingw32-nm
          AS: x86_64-w64-mingw32-as
          STRIP: x86_64-w64-mingw32-strip
          WINRC: x86_64-w64-mingw32-windres
          RANLIB: x86_64-w64-mingw32-ranlib
          DLLTOOL: x86_64-w64-mingw32-dlltool
        run: |
          ./waf configure --dist-target=mingw --ptformat --optimize --windows-vst --with-backends=jack,portaudio,dummy
          ./waf -j 2
          ./waf i18n
